### ISSUE TITLE
node-firebird-driver-native

### ISSUE THREAD

**Issue by johntom** [Tomas2D/knex-firebird-dialect#351]
Hi 
I' testing with 
firebird 2.5.X 
Windows 10
Nodejs 20.10.0  
The  following code when called from an endpoint
const fbk = await fastify.insertdata2(qrystr)

TIA
John
```
'use strict'
const fp = require('fastify-plugin');
const drive = process.env.drive;//'d'
const getDefaultLibraryFilename = require('node-firebird-driver-native')
var knexLib = require('knex');
const knexFirebirdDialect = require('knex-firebird-dialect').default;
const Checkit = require('checkit');
let fb;

async function getknex(database) {
  let knex = knexLib({
    // client: knexFirebirdDialect.default,
    client: knexFirebirdDialect,
    connection: {
      host: "127.0.0.1",
      port: 3050,
      user: "SYSDBA",
      password: "xxxxxxx",
      database: database,
      lowercase_keys: true,
      pageSize: 8192,
      charset: 'UTF8'
    }
  });
  return knex

}
async function insQuery2(knex, qrystr) {
  return new Promise(async function (resolve, reject) {
    let obj = {};
    let recans = '';
    let checkit = undefined;

 
      await knex
        // .transacting(rtx)
        .returning("id")
        .insert({
          id: 1,
          '"user_name"': 'Tomáš 😎',
          '"role"': 'user',
          '"binary_data"': Buffer.from("Binary data for Tomáš 😎"),
         '"status"': 'A',
        })
         .into('"users"');
        
      return resolve({ 'data': obj })
    })
  
}
fastify.decorate('insertdata2', async function (qrystr) {
    let knex = await getknex(qrystr.database);
    let rez = await insQuery2(knex, qrystr)
    await knex.destroy()
    return rez
  })
```

raises 
```Process exited with code 1
Error: Cannot load Firebird client library: 'fbclient.dll'.
    at new ClientImpl (d:\fastify-gp\_live\mongodonBRMNode20KNEX\node_modules\node-firebird-driver-native\dist\lib\client.js:19:26)
    at Object.createNativeClient (d:\fastify-gp\_live\mongodonBRMNode20KNEX\node_modules\node-firebird-driver-native\dist\lib\client.js:12:12)
 ```

**Comment by Tomas2D** [comment]
Hey!

From the README:
>The purpose of doing this is to replace old unmaintained libraries; this one is based on [igorklopov/firebird-knex](https://github.com/igorklopov/firebird-knex). Under the hood, there is a [node-firebird-driver-native](https://github.com/asfernandes/node-firebird-drivers/blob/master/packages/node-firebird-driver-native/). In case you can't use the node-firebird-driver-native package, stick to version 1.x of this package which works on top of [node-firebird](https://github.com/hgourvest/node-firebird) package.

Hence, you need a locally installed Firebird Server (or at least compiled libraries) to run it.

**Comment by johntom** [comment]
Ok, just making sure I didn't do anything wrong.
Thanks
